/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminNotesRouteImport } from './routes/admin/notes'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminNotesNewRouteImport } from './routes/admin/notes/new'
import { Route as AdminNotesIdEditRouteImport } from './routes/admin/notes/$id.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminNotesNewRoute = AdminNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminNotesRoute,
} as any)
const AdminNotesIdEditRoute = AdminNotesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notes': typeof AdminNotesRouteWithChildren
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/notes/new': typeof AdminNotesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/notes/$id/edit': typeof AdminNotesIdEditRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notes': typeof AdminNotesRouteWithChildren
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/notes/new': typeof AdminNotesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/notes/$id/edit': typeof AdminNotesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notes': typeof AdminNotesRouteWithChildren
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/notes/new': typeof AdminNotesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/notes/$id/edit': typeof AdminNotesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/setup'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/notes'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/notes/new'
    | '/admin/users/$userId'
    | '/admin/notes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/setup'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/notes'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/notes/new'
    | '/admin/users/$userId'
    | '/admin/notes/$id/edit'
  id:
    | '__root__'
    | '/admin'
    | '/login'
    | '/setup'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/notes'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/notes/new'
    | '/admin/users/$userId'
    | '/admin/notes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/notes/new': {
      id: '/admin/notes/new'
      path: '/new'
      fullPath: '/admin/notes/new'
      preLoaderRoute: typeof AdminNotesNewRouteImport
      parentRoute: typeof AdminNotesRoute
    }
    '/admin/notes/$id/edit': {
      id: '/admin/notes/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/notes/$id/edit'
      preLoaderRoute: typeof AdminNotesIdEditRouteImport
      parentRoute: typeof AdminNotesRoute
    }
  }
}

interface AdminNotesRouteChildren {
  AdminNotesNewRoute: typeof AdminNotesNewRoute
  AdminNotesIdEditRoute: typeof AdminNotesIdEditRoute
}

const AdminNotesRouteChildren: AdminNotesRouteChildren = {
  AdminNotesNewRoute: AdminNotesNewRoute,
  AdminNotesIdEditRoute: AdminNotesIdEditRoute,
}

const AdminNotesRouteWithChildren = AdminNotesRoute._addFileChildren(
  AdminNotesRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNotesRoute: typeof AdminNotesRouteWithChildren
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommentsRoute: AdminCommentsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNotesRoute: AdminNotesRouteWithChildren,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
